### ISSUE TITLE
about feature extraction

### ISSUE THREAD

**Issue by sunnymoon155** [JJBOY/BMN-Boundary-Matching-Network#10]
Hi, thanks for the code. I'd like to try this on my own datasets, but when I was extracting features by using TSN, I can only get RGB.jpg and Flow_x_y.jpg. How can I get csv features which is used in your code? (like csv_mean_100/v_oOnKQgQZOZ0.csv) Or can I use jpg to do training and testing?

**Comment by JJBOY** [comment]
Please follow the TSN's guide. You only get RGB and Flow because you only used dense flow to the original videos. You should use TSN network the get features.

**Comment by semchan** [comment]
> Please follow the TSN's guide. You only got RGB and Flow because you only used dense flow to the original videos. You should use TSN network to get features then.

Thanks for your great work. If I want only use RGB features of the anet v1.3 which the author provided, is that I can only use the first 200 feature's in the .csv file? thanks a lot.
