### ISSUE TITLE
Non-ASCII character '\xe9' in file main.py

### ISSUE THREAD

**Issue by Light--** [JJBOY/BMN-Boundary-Matching-Network#13]
Maybe Chinese characters need to be handled...

```
$ sh bmn.sh
  File "main.py", line 136
SyntaxError: Non-ASCII character '\xe9' in file main.py on line 136, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
  File "main.py", line 136
SyntaxError: Non-ASCII character '\xe9' in file main.py on line 136, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

```

**Comment by JJBOY** [comment]
Well, the Chinese is commented. If your editor doesn't support for Chinese, you can remove it.

**Comment by Light--** [comment]
> e is commented. If your editor doesn't support for Chinese, you can remove it

i didn't use an editor or IDE, only run the script in ubuntu shell ....

**Comment by JJBOY** [comment]
That's strange. I never meet this problem. You can just try to remove all the Chinese comments.

**Comment by adalisan** [comment]
python2 has this problem. code needs to be fixed to make it back-compatible with python2
