### ISSUE TITLE
the pth file cannot be decompressed

### ISSUE THREAD

**Issue by Light--** [JJBOY/BMN-Boundary-Matching-Network#14]
i download the ``` BMN_best.pth.tar``` from the BaiduYun(pan.baidu.com) link u provided, for 2 times, both cannot be decompressed.

```
>tar -xvf BMN_best.pth.tar
tar: Error opening archive: Unrecognized archive format
```

Could u pls. help to check if the compressed file corrupted?

**Comment by JJBOY** [comment]
The files don't need to be decompressed.

**Comment by Light--** [comment]
> The files don't need to be decompressed.

only rename it to ```BMN_best.pth ``` ?

**Comment by JJBOY** [comment]
You need't to do any thing. This problem you can solve it by yourself if you look at the code. 
    checkpoint = torch.load(opt["checkpoint_path"] + "/BMN_best.pth.tar")

**Comment by Light--** [comment]
> You need't to do any thing. You can find the answer by yourself if you look at the code.
> https://github.com/JJBOY/BMN-Boundary-Matching-Network/blob/45d05146822b85ca672b65f3d030509583d0135a/main.py#L110

Okay, then i need to create a folder named "checkpoint" and put the file in it, right?

**Comment by dpj-dpj** [comment]
how can we get the file BMN_best.pth.tar?
