### ISSUE TITLE
The training takes 10 hours to finish?

### ISSUE THREAD

**Issue by Rheelt** [JJBOY/BMN-Boundary-Matching-Network#16]
Thank you for your code. I find the training process very slow.

**Comment by JJBOY** [comment]
yes, but i have no idea to speed it up without changing its function.  
Another way to make it faster may be using more gpus or using apex for Mixed Precision training.

**Comment by kunli-cs** [comment]
@Rheelt You can accelerate the training process by setting the stride in [conv3d layer](https://github.com/JJBOY/BMN-Boundary-Matching-Network/blob/45d05146822b85ca672b65f3d030509583d0135a/models.py#L51) to (32, 1, 1).
