### ISSUE TITLE
How does the author turn unequal video into equal length? rescaled the feature length of all videos to same length 100,

### ISSUE THREAD

**Issue by Niclaus233** [JJBOY/BMN-Boundary-Matching-Network#28]
Is each video  sampled at different intervals
How does the author turn unequal video into equal length? rescaled the feature length of all videos to same length 100,

**Comment by Frostinassiky** [comment]
The author released the rescaling code in BSN repo:
https://github.com/wzmsltw/BSN-boundary-sensitive-network/blob/master/data/activitynet_feature_cuhk/data_process.py

**Comment by xdw1995** [comment]
> The author released the rescaling code in BSN repo:
> https://github.com/wzmsltw/BSN-boundary-sensitive-network/blob/master/data/activitynet_feature_cuhk/data_process.py

The feature length of one frame about RGB and flow must be 400?
