### ISSUE TITLE
Question about how to get the weight 

### ISSUE THREAD

**Issue by WhoSJackie** [JJBOY/BMN-Boundary-Matching-Network#29]
i have a little confused about the get of the weight in the BM layer in paper,could you please tell me how does it work.

**Comment by JJBOY** [comment]
It's just a sampling process.  It calculates the sampling points for 10000 proposals simultaneously. It is clear described in the paper. or you can find more details in the code.

**Comment by WhoSJackie** [comment]
ok thank you ,i got it.
