### ISSUE TITLE
Have u successfully trained this model by using multiple GPUS?

### ISSUE THREAD

**Issue by yklilfft** [JJBOY/BMN-Boundary-Matching-Network#3]
When I tried to train the model by using nn.DataParallel in pytorch, Runtime error occurred:

> RuntimeError: arguments are located on different GPUs

However , I can train BSN by simply parallel model on multiple GPUS.

Do u have any idea about it?

**Comment by JJBOY** [comment]
of course. In the code I released，the bm mask matrix is a FloatTensor，it's not a component of a module.if you want to train on multi GPUs you should register the bm mask to the torch.nn.Parameter to register it to the module so when you use the  nn.DataParallel, it will auto have a bm mask in every GPUs.

you should do like this:
```
self.bm_mask = nn.Parameter(bm_mask.view(self.temporal_dim, -1),requires_grad=False)
```
and when you give the parameter to the optimizer, you shuold filter the bm mask out.

**Comment by yklilfft** [comment]
Thanks very much about that！
