### ISSUE TITLE
Anyone reproduce the results on THUMOS14?

### ISSUE THREAD

**Issue by 812618101** [JJBOY/BMN-Boundary-Matching-Network#31]
There could be some difference on preprocessing between THUMOS14 and ActivityNet. Anyone reproduce the results on THUMOS14??

**Comment by Aries5522** [comment]
Do you have the data preprocessing code for THUMOS14?

**Comment by JosephineRabbit** [comment]
I have the same question. Can the author kindly provide the thumos14 features and code for data processing?

**Comment by JJBOY** [comment]
You can find the THUMOS14 features here: https://github.com/frostinassiky/gtad

**Comment by doudou123456** [comment]
> There could be some difference on preprocessing between THUMOS14 and ActivityNet. Anyone reproduce the results on THUMOS14??

hello，do you know how to do the preprocessing on THUMOS14

**Comment by JJBOY** [comment]
I&nbsp;can&nbsp;reproduce&nbsp;the&nbsp;similar results&nbsp;on&nbsp;THUMOS14.&nbsp;I&nbsp;have&nbsp;plan&nbsp;to&nbsp;release&nbsp;the&nbsp;code&nbsp;later，&nbsp;_Originally posted by @JJBOY in https://github.com/JJBOY/BMN-Boundary-Matching-Network/issues/39#issuecomment-712955795_.
If you are in hury, you can refer to the code of gtad. In fact, my code on THUMOS is also based on his code.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "doudou123456"<notifications@github.com&gt;; 
发送时间: 2020年10月21日(星期三) 下午2:57
收件人: "JJBOY/BMN-Boundary-Matching-Network"<BMN-Boundary-Matching-Network@noreply.github.com&gt;; 
抄送: "Hello World"<1135869534@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [JJBOY/BMN-Boundary-Matching-Network] Anyone reproduce the results on THUMOS14? (#31)





  
There could be some difference on preprocessing between THUMOS14 and ActivityNet. Anyone reproduce the results on THUMOS14??
  
hello，do you know how to do the preprocessing on THUMOS14

**Comment by doudou123456** [comment]
> I&nbsp;can&nbsp;reproduce&nbsp;the&nbsp;similar results&nbsp;on&nbsp;THUMOS14.&nbsp;I&nbsp;have&nbsp;plan&nbsp;to&nbsp;release&nbsp;the&nbsp;code&nbsp;later，&nbsp;_Originally posted by @JJBOY in [#39 (comment)](https://github.com/JJBOY/BMN-Boundary-Matching-Network/issues/39#issuecomment-712955795_). If you are in hury, you can refer to the code of gtad. In fact, my code on THUMOS is also based on his code.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "doudou123456"<notifications@github.com&gt;; 发送时间: 2020年10月21日(星期三) 下午2:57 收件人: "JJBOY/BMN-Boundary-Matching-Network"<BMN-Boundary-Matching-Network@noreply.github.com&gt;; 抄送: "Hello World"<1135869534@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [JJBOY/BMN-Boundary-Matching-Network] Anyone reproduce the results on THUMOS14? (#31) There could be some difference on preprocessing between THUMOS14 and ActivityNet. Anyone reproduce the results on THUMOS14?? hello，do you know how to do the preprocessing on THUMOS14 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

If possible, could you share your code on THUMOS. best great!!

**Comment by mugenggeng** [comment]
Excuse me, did you reproduce the results later on THUMOS
