### ISSUE TITLE
About the label and the best_loss

### ISSUE THREAD

**Issue by doudou123456** [JJBOY/BMN-Boundary-Matching-Network#37]
谢谢你的工作，但是在你最新的代码中，opt文件中的"video_info_backup.csv"文件和"anet_anno_action_backup.json"文件好像没有提供，使用的还是之前的label文件？
另外一个问题是：在训练过程中，你使用了best_loss变量，按照我的理解，这应该是一个局部变量，每一个epoch都会初始化为一个极大的值，而每一次保存都是会保存当前epoch的参数？请你确认一下。

**Comment by JJBOY** [comment]
上传的时候忘记修改了，&nbsp;上面两个文件跟之前BSN提供的是一样，改一下名字就行了。best_loss应该是一个全局变量，应该在训练过程中维护同一个值，不过现在这样是用了最后一个epoch的模型，影响也不大。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "doudou123456"<notifications@github.com&gt;; 
发送时间: 2020年9月22日(星期二) 下午3:28
收件人: "JJBOY/BMN-Boundary-Matching-Network"<BMN-Boundary-Matching-Network@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [JJBOY/BMN-Boundary-Matching-Network] About the label and the best_loss (#37)





 
谢谢你的工作，但是在你最新的代码中，opt文件中的"video_info_backup.csv"文件和"anet_anno_action_backup.json"文件好像没有提供，使用的还是之前的label文件？
 另外一个问题是：在训练过程中，你使用了best_loss变量，按照我的理解，这应该是一个局部变量，每一个epoch都会初始化为一个极大的值，而每一次保存都是会保存当前epoch的参数？请你确认一下。

**Comment by doudou123456** [comment]
好的 麻烦了
