### ISSUE TITLE
The effect of temporal scale on this model and hyperparameters.

### ISSUE THREAD

**Issue by takfate** [JJBOY/BMN-Boundary-Matching-Network#45]
In default BMN, the temporal scale is 100.
if I want to generate `200*200 proposal map` by feature with 200-length, need I change some hyperparameters ?

For instance, need I change the positive threshold of `cls_pem_loss` or three thresholds of `reg_pem_loss` ?
Is there anything else that needs to be modified

**Comment by JJBOY** [comment]
As a matter of necessity, no hyper-parameters need to be changed. You only need to change `temporal_scale` from 100 to 200. But tuning the parameters can make all the difference in performance. In my experience, you can try to reduce `num_sample` or `num_sample_perbin` to reduce computation without degrading performance. You can also adjust the other hyperparameters to try.

**Comment by takfate** [comment]
> As a matter of necessity, no hyper-parameters need to be changed. You only need to change `temporal_scale` from 100 to 200. But tuning the parameters can make all the difference in performance. In my experience, you can try to reduce `num_sample` or `num_sample_perbin` to reduce computation without degrading performance. You can also adjust the other hyperparameters to try.

Thanks a lot!

**Comment by xianguo-dev** [comment]
> 

Hi! I'd like to know how to generate 200*200 proposal map by feature with **200**-length? Although I have trained the TSN model, I don't know how to generate feature. Would you please share your code? Thanks a lot!
