### ISSUE TITLE
why the training of BMN get stuck?

### ISSUE THREAD

**Issue by Zhuysheng** [JJBOY/BMN-Boundary-Matching-Network#5]
python main.py  --module BMN --mode train

train subset video numbers: 9649
validation subset video numbers: 4728

then get stuck

**Comment by Zhuysheng** [comment]
@JJBOY thanks，nearly one hour, but why it takes such a long time for one epoch?

**Comment by JJBOY** [comment]
because it calculates all the proposal's(100x100) confidence for each video, which is time consuming.
