### ISSUE TITLE
Could I share your well-trained models on THUMOS 2014?

### ISSUE THREAD

**Issue by junmuzi** [JJBOY/BMN-Boundary-Matching-Network#7]
Hi,

Could I share your well-trained models on THUMOS 2014? 

By the way, why BMN_best.pth.tar model can not be decompressed? Seems this tar file is broken. 

Best Regards,
Jun Li

**Comment by JJBOY** [comment]
First, I don't train any model on THUMOS2014.
Second, the compressed model doesn't need to be decompressd. You can load it without any additional operation.
