### ISSUE TITLE
Code for activity detection

### ISSUE THREAD

**Issue by SilvioGiancola** [JJBOY/BMN-Boundary-Matching-Network#9]
Dear authors,
Thank you for sharing the code of your recent paper BMN. I was wondering if you could also share the code you used for activity detection on ActivityNet (Results from Table 6 of your paper). 
Any guidelines to classify your proposals afterwards, and reproduce the results of your paper?
Thank you for you support,
Best,

**Comment by JJBOY** [comment]
Sorry for making you misunderstanding, I am not author of the paper and this codebase is also not the offical implementation. I will try to finish the detection part but i am so busy recently. So you may have to find another codebase if you need it urgently.
